# Generated by Django 2.0.5 on 2018-10-06 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='text_contents',
            new_name='body',
        ),
    ]
