# Generated by Django 2.0.5 on 2018-10-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_remove_article_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='time_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
