# Generated by Django 2.0.5 on 2018-10-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20181014_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.TextField(blank=True, null=True),
        ),
    ]
